import pandas as pd
df = pd.read_excel(r'data/MS_spectrum_data.xlsx')
print(f'Shape: {df.shape}')
print(f'Columns: {list(df.columns)}')
print(f'Unnamed non-null: {df["Unnamed: 7"].notna().sum()}')
print(f'Unique chemicals: {df["chemical_name"].nunique()}')
print(f'Unique CAS: {df["CAS"].nunique()}')
print(f'Unique numbers: {df["number"].nunique()}')
print(f'MW range: {df["MW"].min():.3f} ~ {df["MW"].max():.3f}')
gs = df.groupby("chemical_name").size()
print(f"Avg rows/chem: {gs.mean():.1f}, Max: {gs.max()}, Single: {(gs==1).sum()}")
print(f"First mz: {repr(df.iloc[0]['mz'])}")
print(f"First int: {repr(df.iloc[0]['intensity'])}")
mzc = df["mz"].apply(lambda x: len(str(x).split(",")) if pd.notna(x) else 0)
intc = df["intensity"].apply(lambda x: len(str(x).split(",")) if pd.notna(x) else 0)
print(f"mz range: {mzc.min()}~{mzc.max()}, int range: {intc.min()}~{intc.max()}")
print(f"Misaligned: {(mzc!=intc).sum()}")
