import pandas as pd, numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
import matplotlib.ticker as tk
OUT=Path("output")
FIG=Path("output")
print("[Viz] Loading...")
df=pd.read_parquet(OUT/"combined.parquet")
sf=pd.read_parquet(OUT/"stage2_features.parquet")
imp=pd.read_parquet(OUT/"feature_importance.parquet")
print("  1: DBE distribution...")
fig,ax=plt.subplots(figsize=(10,4))
dbe=df["DBE"].clip(0,20)
ax.hist(dbe,bins=40,color="#2196F3",edgecolor="white",lw=0.3)
ax.set_xlabel("DBE")
ax.set_ylabel("Count")
ax.yaxis.set_major_formatter(tk.FuncFormatter(lambda x,_:str(round(x/1000))+"k"))
ax.axvline(dbe.median(),color="red",ls="--",alpha=0.5)
plt.tight_layout()
fig.savefig(OUT/"viz_dbe_dist.png",dpi=150)
plt.close()
print("  2: Van Krevelen...")
samp=df.sample(min(10000,len(df)),random_state=42)
fig,ax=plt.subplots(figsize=(8,6))
sc=ax.scatter(samp["OC"],samp["HC"],c=samp["DBE"].clip(0,15),s=5,alpha=0.5,cmap="viridis",edgecolors="none")
fig.colorbar(sc,ax=ax,label="DBE")
ax.set_xlabel("O/C Ratio");ax.set_ylabel("H/C Ratio")
ax.set_title("Van Krevelen (10k sample)")
ax.set_xlim(-0.02,1.02);ax.set_ylim(0,2.5)
reg=[("Lipids/FA",.05,.2,1.5,2.0),("Lignin",.1,.4,.7,1.5),("Carb",.5,1.0,1.5,2.0),("Aromatics",0,.3,.3,.8)]
for n,x1,x2,y1,y2 in reg:
 ax.annotate(n,xy=((x1+x2)/2,(y1+y2)/2),ha="center",va="center",alpha=0.4,fontsize=8,bbox=dict(boxstyle="round",fc="lightgray",alpha=0.15))
plt.tight_layout()
fig.savefig(OUT/"viz_van_krevelen.png",dpi=150)
plt.close()
print("  3: Top m/z importance...")
spec_imp=imp[imp["feature"].str.startswith("mz")]
top=spec_imp.nlargest(20,"importance")
top["mz"]=top["feature"].str.extract(r"(\d+)").astype(int)
fig,ax=plt.subplots(figsize=(10,6))
colors=["#e74c3c" if m in[77,91,51] else"#3498db" for m in top["mz"]]
ax.barh(range(20),top["importance"],color=colors,height=0.7)
ax.set_yticks(range(20))
ax.set_yticklabels(["m/z "+str(m) for m in top["mz"]])
ax.invert_yaxis()
ax.set_xlabel("Importance")
ax.set_title("Top 20 m/z for DBE Prediction")
from matplotlib.patches import Rectangle as R
ax.legend(handles=[R((0,0),1,1,color="#e74c3c",label="Aromatic marker"),R((0,0),1,1,color="#3498db",label="Other")],loc="lower right")
L={77:"C6H5+",91:"C7H7+",51:"C4H3+"}
for i,(_,r) in enumerate(top.iterrows()):
 if r["mz"] in L:
  ax.annotate(L[r["mz"]],xy=(r["importance"],i),xytext=(5,0),textcoords="offset points",fontsize=7,alpha=0.6)
plt.tight_layout()
fig.savefig(OUT/"viz_top_mz.png",dpi=150)
plt.close()
print("  4: Entropy + Fragments...")
fig,ax=plt.subplots(figsize=(10,4))
ent=sf["spectral_entropy"]
ax.hist(ent,bins=80,color="#9C27B0",edgecolor="white",lw=0.2,alpha=0.8)
ax.set_xlabel("Spectral Entropy (bits)")
ax.set_ylabel("Count")
ax.axvline(ent.median(),color="red",ls="--",alpha=0.5)
plt.tight_layout()
fig.savefig(OUT/"viz_entropy.png",dpi=150)
plt.close()
fig,ax=plt.subplots(figsize=(10,4))
nf=sf["n_fragments"].clip(0,100)
ax.hist(nf,bins=80,color="#FF9800",edgecolor="white",lw=0.2,alpha=0.8)
ax.set_xlabel("Fragments")
ax.set_ylabel("Count")
ax.axvline(nf.median(),color="red",ls="--",alpha=0.5)
plt.tight_layout()
fig.savefig(OUT/"viz_fragments.png",dpi=150)
plt.close()
print("All done!")
